name: Build iOS Dev Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo & dependencies
        run: |
          npm install -g expo-cli
          npm ci

      - name: Add expo-dev-client
        run: npx expo install expo-dev-client
        
      - name: Prebuild and Install CocoaPods
        run: |
          npx expo prebuild --platform ios --clean
          cd ios
          pod install
      
      - name: Build iOS archive (unsigned)
        run: |
          xcodebuild \
            -workspace ios/sparklines.xcworkspace \
            -scheme sparklines \
            -configuration Debug clean archive \
            -sdk iphoneos \
            -archivePath build/sparklines.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Export IPA
        run: |
          cd build/sparklines.xcarchive/Products/Applications
          mkdir -p Payload
          cp -r Sparklines.app Payload/
          zip -r sparklines.ipa Payload
          mv sparklines.ipa $GITHUB_WORKSPACE/
      
      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: sparklines-ipa
          path: sparklines.ipa
