name: Build Unsigned iOS Dev Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo & dependencies
        run: |
          npm install -g expo-cli
          npm ci

      - name: Prebuild and Install CocoaPods
        run: |
          npx expo prebuild --platform ios --clean
          cd ios
          pod install

      - name: Create ExportOptions.plist
        run: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOF
          
      - name: Patch AutoSizingStack.swift
        run: |
          sed -i '' '/\.onGeometryChange/d' node_modules/expo-modules-core/ios/Core/Views/SwiftUI/AutoSizingStack.swift

      - name: List Scheme
        run: |
          cd ios
          xcodebuild -list -workspace sparklines.xcworkspace
      
      - name: Build iOS archive (unsigned)
        run: |
          xcodebuild \
            -workspace sparklines.xcworkspace \
            -scheme sparklines \
            -configuration Release clean archive \
            -sdk iphoneos \
            -archivePath ../build/sparklines.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ../build/sparklines.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build/IPAExport
          mv build/IPAExport/sparklines.ipa $GITHUB_WORKSPACE/

      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: sparklines-ipa
          path: sparklines.ipa
