name: Build Unsigned IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo & dependencies
        run: |
          npm install -g expo-cli
          npm ci

      - name: Run Expo prebuild
        run: npx expo prebuild --platform ios --clean

      - name: Install Ruby & Fastlane
        run: |
          sudo gem install fastlane
          cd ios && pod install

      - name: Run Fastlane
        run: |
          cd ios
          fastlane build_unsigned

      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: sparklines-ipa
          path: ios/build/*.ipa
