name: Build Unsigned iOS Dev Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo & dependencies
        run: |
          npm install -g expo-cli
          npm ci

      - name: Run Expo prebuild
        run: npx expo prebuild --platform ios --clean

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -v 1.15.2
          cd ios
          pod install

      - name: Build iOS .app (unsigned)
        run: |
          cd ios
          xcodebuild -workspace sparklines.xcworkspace \
            -scheme sparklines \
            -configuration Debug \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY=""

      - name: Package .ipa
        run: |
          mkdir -p Payload
          cp -r ios/build/Build/Products/Release-iphoneos/sparklines.app Payload/
          zip -r sparklines.ipa Payload
          mv sparklines.ipa $GITHUB_WORKSPACE

      - name: Upload .ipa
        uses: actions/upload-artifact@v4
        with:
          name: sparklines-ipa
          path: sparklines.ipa
